# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.0
group=games.enchanted.f3teverywhere
java_version=21

# Common
mod_version=2.2.0
mod_name=Debug Keys Everywhere
mod_author=Enchanted_Games
mod_id=eg_f3_t_everywhere
license=CC BY-NC 4.0
credits=
description=A simple utility mod that lets you reload resourcepacks with the F3 + T keybind while a screen is open, speeding up resourcepack development. Also allows using other debug keybinds, such as F3 + H, when a screen is open. 

mod_homepage=https://github.com/Enchanted-Games/f3-t-everywhere
mod_issues=https://github.com/Enchanted-Games/f3-t-everywhere/issues
#mod_source only used in fabric mod json
mod_source=https://github.com/Enchanted-Games/f3-t-everywhere
minecraft_neoforge_version_range=(1.21.5,)
minecraft_fabric_version_range=">1.21.5"

minecraft_version=25w20a
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=25w20a-20250513.154825
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.5
parchment_version=2025.04.19

# Fabric
## https://fabricmc.net/develop/
fabric_version=0.124.1+1.21.6
fabric_loader_version=0.16.14

# NeoForge
## https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.5.66-beta
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true